//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pluralize.NET.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pluralize.NET.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fish,fish
        ///media,media
        ///moose,moose
        ///sheep,sheep
        ///series,series
        ///species,species
        ///agenda,agenda
        ///news,news
        ///reindeer,reindeer
        ///starfish,starfish
        ///smallpox,smallpox
        ///chickenpox,chickenpox
        ///shambles,shambles
        ///garbage,garbage
        ///you,you
        ///wildlife,wildlife
        ///Staff,Staff
        ///STAFF,STAFF
        ///veniam,veniam
        ///this,these
        ///that,those
        ///is,are
        ///man,men
        ///superman,supermen
        ///ox,oxen
        ///bus,buses
        ///airbus,airbuses
        ///railbus,railbuses
        ///wife,wives
        ///guest,guests
        ///thing,things
        ///mess,messes
        ///guess,guesses
        ///person,people
        ///meteor,meteors
        ///chat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputData {
            get {
                return ResourceManager.GetString("InputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dingo,dingos
        ///mango,mangoes
        ///echo,echos
        ///ghetto,ghettoes
        ///nucleus,nucleuses
        ///bureau,bureaux
        ///seraph,seraphs.
        /// </summary>
        internal static string PluralToSingularExceptions {
            get {
                return ResourceManager.GetString("PluralToSingularExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dingo,dingos
        ///mango,mangoes
        ///echo,echos
        ///ghetto,ghettoes
        ///nucleus,nucleuses
        ///bureau,bureaux
        ///seraph,seraphs.
        /// </summary>
        internal static string SingularToPluralExceptions {
            get {
                return ResourceManager.GetString("SingularToPluralExceptions", resourceCulture);
            }
        }
    }
}
